spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
---
spring.config.activate.on-profile:
  - prod
  - dev
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      data-locations: classpath:sql/init_data.sql

---
spring.config.activate.on-profile: test
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      generate-ddl: true
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2